version: '3'

services:
  minio:
    image: 'minio/minio:RELEASE.2020-01-16T03-05-44Z'
    command: server /data
    container_name: 'minio'
    ports:
      - '9001:9000'
    volumes:
      - ./data/minio:/data
    networks:
      - spotter
    environment:
      MINIO_ACCESS_KEY: 'minio'
      MINIO_SECRET_KEY: 'minio123'

networks:
  spotter:
    external: true